alias mkdatedir="mkdir $(date +%Y-%m-%d)"
alias datestr="date +%Y-%m-%dT%H:%M:%S"
alias open_latest_screenshot='open $HOME/Pictures/Screenshots/"$(ls -t $HOME/Pictures/Screenshots/ | head -n1)"'
alias latest_download='echo $HOME/Downloads/"$(ls -t $HOME/Downloads | head -n1)"'
